[build]
  command = "npm cache clean --force && npm install --os=linux --ignore-engines  && npm run build"
  publish = "out"  

[[redirects]]
  from = "/user/reports/:path"
  to = "https://app.sheetwa.com/user/reports/:path"
  status = 302
  force = true

[[redirects]]
  from = "/user/:path"
  to = "https://app.sheetwa.com/user/:path"
  status = 302
  force = true

# Redirect blog URLs without trailing slash to versions with trailing slash (internal redirect)
[[redirects]]
  from = "/blogs/:splat"
  to = "/blogs/:splat/"
  status = 301
  force = true

# Handle the blog root
[[redirects]]
  from = "/blogs"
  to = "https://sheetwa222.netlify.app"
  status = 200
  force = true

# Handle blog URLs with trailing slash
[[redirects]]
  from = "/blogs/:splat/"
  to = "https://sheetwa222.netlify.app/:splat/"
  status = 200
  force = true