[build]
  command = "npm cache clean --force && npm install --os=linux --ignore-engines  && npm run build"
  publish = "out"  

[[redirects]]
  from = "/user/:path*"
  to = "https://app.sheetwa.com/user/:path*"
  status = 302
  force = true

[[redirects]]
  from = "/blogs/:splat"
  to = "https://sheetwa22.getpowerblog.com/blogs/:splat"
  status = 200
  force = true