[build]
  command = "npm cache clean --force && npm install --os=linux --ignore-engines  && npm run build"
  publish = "out"  

from = "/user/*"
  to = "https://app.sheetwa.com/user/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/blogs"
  to = "https://sheetwa22.getpowerblog.com"
  status = 200
  force = true

[[redirects]]
  from = "/blogs/:splat"
  to = "https://sheetwa22.getpowerblog.com/:splat"
  status = 200
  force = true