[build]
  command = "npm cache clean --force && npm install --os=linux --ignore-engines  && npm run build"
  publish = "out"  

[[redirects]]
  from = "/user/reports/:path"
  to = "https://app.sheetwa.com/user/reports/:path"
  status = 302
  force = true

[[redirects]]
  from = "/user/:path"
  to = "https://app.sheetwa.com/user/:path"
  status = 302
  force = true

[[edge_functions]]
  path = "/blogs"
  function = "redirect"

[[edge_functions]]
  path = "/blogs/*"
  function = "redirect"

  