[build]
  command = "npm cache clean --force && npm install --os=linux --ignore-engines && npm run build"
  publish = "out"

# Redirect user report routes to app.sheetwa.com
[[redirects]]
  from = "/user/reports/:path"
  to = "https://app.sheetwa.com/user/reports/:path"
  status = 302
  force = true

# Redirect all /user/* routes
[[redirects]]
  from = "/user/:path"
  to = "https://app.sheetwa.com/user/:path"
  status = 302
  force = true

# Enforce trailing slashes on blog URLs BEFORE anything else
[[redirects]]
  from = "/blogs/:splat"
  to = "/blogs/:splat/"
  status = 301
  force = true

# Serve blog content ONLY on /blogs/* with trailing slash
[[redirects]]
  from = "/blogs/:splat/"
  to = "https://sheetwa222.netlify.app/:splat/"
  status = 200
  force = true
  conditions = { Host = ["comfy-elf-57eb7e.netlify.app"] }

# Redirect /blogs root with and without trailing slash
[[redirects]]
  from = "/blogs"
  to = "https://sheetwa222.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/blogs/"
  to = "https://sheetwa222.netlify.app/"
  status = 200
  force = true
  conditions = { Host = ["comfy-elf-57eb7e.netlify.app"] }
